DOG_BREEDS = [
    {
        "species": "dog",
        "name": "Labrador Retriever",
        "name_en": "Labrador Retriever",
        "origin": "Canadá/Reino Unido",
        "size": "large",
        "weight_range": "25-36 kg",
        "life_expectancy": "10-12 anos",
        "temperament": ["amigável", "ativo", "leal", "brincalhão", "obediente", "gentil"],
        "energy_level": 4,
        "grooming_level": 2,
        "health_issues": ["displasia de quadril", "obesidade", "problemas oculares", "displasia de cotovelo"],
        "exercise_needs": "Necessita de pelo menos 1-2 horas de exercício diário. Adora nadar, buscar objetos e atividades ao ar livre.",
        "feeding_guide": "Adultos: 300-400g de ração premium por dia, divididos em 2 refeições. Monitorar peso pois são propensos à obesidade. Filhotes seguir orientação do veterinário.",
        "care_tips": ["Escovar a pelagem 2-3 vezes por semana", "Limpar as orelhas semanalmente", "Controlar o peso rigorosamente", "Socialização desde filhote é essencial"],
        "ideal_environment": "Adapta-se bem em casas com quintal, mas pode viver em apartamentos com exercício suficiente. Precisa de companhia humana e não suporta ficar sozinho por longos períodos.",
        "description": "O Labrador Retriever é uma das raças mais populares do mundo, conhecida por sua personalidade amigável e versátil. É excelente como cão de família, de serviço, de busca e salvamento. Sua lealdade e inteligência o tornam um companheiro ideal para famílias com crianças.",
    },
    {
        "species": "dog",
        "name": "Golden Retriever",
        "name_en": "Golden Retriever",
        "origin": "Escócia/Reino Unido",
        "size": "large",
        "weight_range": "25-34 kg",
        "life_expectancy": "10-12 anos",
        "temperament": ["confiável", "confiante", "amistoso", "gentil", "inteligente", "carinhoso"],
        "energy_level": 4,
        "grooming_level": 3,
        "health_issues": ["displasia de quadril", "câncer", "problemas cardíacos", "problemas oculares", "displasia de cotovelo"],
        "exercise_needs": "Requer 1-2 horas de exercício diário. Adora nadar, correr e brincar de buscar objetos. Excelente para esportes caninos.",
        "feeding_guide": "Adultos: 300-400g de ração premium por dia em 2 refeições. Evitar superalimentação pois tendem ao sobrepeso. Ômega-3 beneficia a pelagem.",
        "care_tips": ["Escovação 3-4 vezes por semana para evitar nós", "Banho mensal ou quando necessário", "Verificar e limpar orelhas semanalmente", "Manter dentes limpos"],
        "ideal_environment": "Ideal em casas com quintal amplo. Pode se adaptar a apartamentos com exercício adequado. Família ativa é o ambiente perfeito para essa raça.",
        "description": "O Golden Retriever é famoso por seu temperamento dócil e sua pelagem dourada característica. É um dos cães mais amados do mundo por sua paciência e gentileza, sendo excelente com crianças e outros animais. Muito utilizado como cão-guia e de terapia.",
    },
    {
        "species": "dog",
        "name": "Bulldog Inglês",
        "name_en": "English Bulldog",
        "origin": "Reino Unido",
        "size": "medium",
        "weight_range": "18-25 kg",
        "life_expectancy": "8-10 anos",
        "temperament": ["calmo", "corajoso", "amigável", "leal", "determinado", "gentil"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["problemas respiratórios (síndrome braquicefálica)", "displasia de quadril", "dermatite nas dobras", "problemas cardíacos", "obesidade"],
        "exercise_needs": "Necessita apenas de exercícios leves, 20-30 minutos por dia. Evitar exercícios intensos especialmente no calor devido aos problemas respiratórios.",
        "feeding_guide": "Adultos: 250-300g por dia em 2 refeições. Muito propenso à obesidade. Evitar exercício após alimentação para prevenir torção gástrica.",
        "care_tips": ["Limpar as dobras da pele diariamente para evitar infecções", "Limpar a prega do nariz regularmente", "Manter fresco no verão", "Evitar exercícios no calor"],
        "ideal_environment": "Perfeito para apartamentos. Não tolera calor excessivo. Boa opção para donos menos ativos que querem um companheiro tranquilo e afetuoso.",
        "description": "O Bulldog Inglês, apesar de sua aparência intimidante, é na verdade um cão extremamente dócil e carinhoso. É ótimo com crianças e tem um temperamento calmo e paciente. Requer cuidados especiais com sua saúde devido às características físicas braquicefálicas.",
    },
    {
        "species": "dog",
        "name": "Poodle",
        "name_en": "Poodle",
        "origin": "França/Alemanha",
        "size": "small",
        "weight_range": "2-30 kg (varia por tipo)",
        "life_expectancy": "12-15 anos",
        "temperament": ["inteligente", "ativo", "alerta", "instintivo", "treinável", "fiel"],
        "energy_level": 4,
        "grooming_level": 5,
        "health_issues": ["problemas oculares", "displasia de quadril (em grandes)", "problemas de tireoide", "epilepsia", "doença de Addison"],
        "exercise_needs": "Necessita de exercício diário moderado a intenso. Adora aprender truques, nadar e atividades mentais estimulantes. Pelo menos 1 hora de atividade diária.",
        "feeding_guide": "Varia muito pelo tamanho: toy 100-150g/dia, miniatura 150-250g/dia, padrão 250-400g/dia de ração premium, divididos em 2 refeições.",
        "care_tips": ["Tosquia profissional a cada 6-8 semanas", "Escovação diária para evitar nós", "Limpeza das orelhas semanal", "Estimulação mental é essencial"],
        "ideal_environment": "Adapta-se a qualquer ambiente, desde apartamentos pequenos até casas grandes. O Poodle Toy e Miniatura são perfeitos para apartamentos. Precisa de estimulação mental constante.",
        "description": "O Poodle é considerado uma das raças mais inteligentes do mundo. Existe em quatro tamanhos: standard, medium, miniatura e toy. Hipoalergênicos, são ótimos para pessoas com alergias. Extremamente treináveis e versáteis, se destacam em obediência, agility e outras atividades.",
    },
    {
        "species": "dog",
        "name": "Pastor Alemão",
        "name_en": "German Shepherd",
        "origin": "Alemanha",
        "size": "large",
        "weight_range": "22-40 kg",
        "life_expectancy": "9-13 anos",
        "temperament": ["corajoso", "confiante", "inteligente", "leal", "protetor", "obediente"],
        "energy_level": 5,
        "grooming_level": 3,
        "health_issues": ["displasia de quadril", "displasia de cotovelo", "mielopatia degenerativa", "bloat", "problemas digestivos"],
        "exercise_needs": "Necessita de 2+ horas de exercício intenso diário. Ideal para esportes caninos, trabalho policial/militar. Precisa de estimulação mental e física constante.",
        "feeding_guide": "Adultos: 350-500g de ração de alta qualidade por dia em 2 refeições. Filhotes precisam de ração específica para raças grandes para desenvolvimento ósseo correto.",
        "care_tips": ["Escovação diária durante muda de pelo", "Exercício intenso diário", "Treinamento de obediência desde filhote", "Socialização ampla é fundamental"],
        "ideal_environment": "Melhor em casas com quintal amplo. Não é recomendado para apartamentos pequenos sem exercício adequado. Precisa de um tutor ativo e comprometido com treinamento.",
        "description": "O Pastor Alemão é uma das raças mais versáteis e inteligentes do mundo. Amplamente utilizado por forças policiais e militares, como cão-guia e em busca e salvamento. É um guardião natural e companheiro extremamente leal à sua família.",
    },
    {
        "species": "dog",
        "name": "Beagle",
        "name_en": "Beagle",
        "origin": "Reino Unido",
        "size": "small",
        "weight_range": "9-11 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["amigável", "curioso", "alegre", "determinado", "sociável", "brincalhão"],
        "energy_level": 4,
        "grooming_level": 2,
        "health_issues": ["obesidade", "epilepsia", "displasia de quadril", "problemas oculares", "hipotireoidismo"],
        "exercise_needs": "Necessita de pelo menos 1 hora de exercício diário. Tem instinto de caça muito forte, então precisa de ambiente seguro. Adora explorar e farejar.",
        "feeding_guide": "Adultos: 200-270g de ração premium por dia em 2 refeições. Muito propenso à obesidade. Não deixar comida sempre disponível.",
        "care_tips": ["Escovação semanal", "Limpeza das orelhas semanalmente (orelhas caídas retém umidade)", "Ambiente cercado é essencial", "Controlar porções alimentares rigorosamente"],
        "ideal_environment": "Adapta-se a apartamentos, mas precisa de exercício diário. Quintal cercado é ideal pois pode escapar seguindo rastros. Muito social e gosta de companhia.",
        "description": "O Beagle é um cão compacto, robusto e cheio de energia, originalmente criado para caça. É extremamente sociável e se dá bem com crianças e outros animais. Sua curiosidade e olfato aguçado o tornam um explorador nato, mas também um desafio para conter em ambientes abertos.",
    },
    {
        "species": "dog",
        "name": "Rottweiler",
        "name_en": "Rottweiler",
        "origin": "Alemanha",
        "size": "large",
        "weight_range": "36-60 kg",
        "life_expectancy": "8-10 anos",
        "temperament": ["leal", "protetor", "obediente", "corajoso", "confiante", "calmo"],
        "energy_level": 3,
        "grooming_level": 2,
        "health_issues": ["displasia de quadril", "displasia de cotovelo", "osteossarcoma", "problemas cardíacos", "obesidade"],
        "exercise_needs": "Necessita de 1-2 horas de exercício diário de intensidade moderada. Trabalho e treinamento de obediência são fundamentais para seu bem-estar mental.",
        "feeding_guide": "Adultos: 400-600g de ração de alta qualidade por dia em 2-3 refeições. Evitar exercício logo após alimentação. Ração específica para raças grandes.",
        "care_tips": ["Treinamento desde filhote é essencial", "Socialização ampla e precoce", "Escovação semanal", "Verificar saúde das articulações regularmente"],
        "ideal_environment": "Melhor em casas com quintal. Precisa de um tutor experiente e consistente. Não é recomendado para donos de primeira viagem sem experiência com raças de grande porte.",
        "description": "O Rottweiler é uma raça poderosa e leal, com histórico de trabalho como cão de guarda e condução de gado. Com socialização e treinamento adequados, é um companheiro dócil e afetuoso com a família. Requer um tutor experiente que estabeleça limites claros desde cedo.",
    },
    {
        "species": "dog",
        "name": "Yorkshire Terrier",
        "name_en": "Yorkshire Terrier",
        "origin": "Reino Unido",
        "size": "small",
        "weight_range": "2-3,5 kg",
        "life_expectancy": "13-16 anos",
        "temperament": ["ousado", "independente", "corajoso", "inteligente", "carinhoso", "espirituoso"],
        "energy_level": 3,
        "grooming_level": 5,
        "health_issues": ["problemas dentários", "hipoglicemia (filhotes)", "luxação de patela", "colapso traqueal", "problemas hepáticos (shunt portossistêmico)"],
        "exercise_needs": "30-45 minutos de exercício diário é suficiente. Apesar do tamanho pequeno, é ativo e gosta de brincar. Caminhadas curtas e brincadeiras internas atendem suas necessidades.",
        "feeding_guide": "Adultos: 80-120g de ração premium para raças pequenas por dia em 3-4 refeições pequenas. Filhotes precisam comer com frequência para evitar hipoglicemia.",
        "care_tips": ["Escovação diária para evitar nós (pelo longo)", "Visitas regulares ao groomer", "Cuidados dentários frequentes", "Proteger do frio com roupinhas"],
        "ideal_environment": "Perfeito para apartamentos. Por seu tamanho pequeno, é fácil de transportar e manter. Apesar do tamanho, é corajoso e se achará o maior de todos.",
        "description": "O Yorkshire Terrier, carinhosamente chamado de Yorkie, é uma raça pequena com personalidade gigante. Apesar do tamanho diminuto, é valente e cheio de energia. Sua pelagem sedosa e longa requer cuidados constantes, mas seu charme e lealdade compensam o esforço.",
    },
    {
        "species": "dog",
        "name": "Chihuahua",
        "name_en": "Chihuahua",
        "origin": "México",
        "size": "small",
        "weight_range": "1,5-3 kg",
        "life_expectancy": "14-16 anos",
        "temperament": ["alerta", "ágil", "corajoso", "leal", "espirituoso", "vivaz"],
        "energy_level": 3,
        "grooming_level": 2,
        "health_issues": ["hipoglicemia", "problemas dentários", "luxação de patela", "hidrocefalia", "colapso traqueal", "problemas cardíacos"],
        "exercise_needs": "20-30 minutos de exercício leve diário. Brincadeiras internas atendem bem suas necessidades. Evitar exercícios excessivos que possam causar hipoglicemia.",
        "feeding_guide": "Adultos: 50-100g de ração premium para raças pequenas por dia em 3-4 refeições pequenas. Atenção especial à hipoglicemia em filhotes.",
        "care_tips": ["Cuidados dentários frequentes", "Proteger do frio (são sensíveis ao frio)", "Socialização cuidadosa com crianças pequenas", "Cuidado ao carregar para não machucar"],
        "ideal_environment": "Ideal para apartamentos pequenos. É o menor cão do mundo e perfeito para quem tem espaço limitado. Gosta de colo e de estar próximo ao tutor.",
        "description": "O Chihuahua é a menor raça de cão do mundo, mas compensa no que lhe falta em tamanho com personalidade ousada e espírito valente. Extremamente leal ao seu tutor, pode ser desconfiante com estranhos. Apesar de pequeno, tem coragem de enfrentar cães muito maiores.",
    },
    {
        "species": "dog",
        "name": "Shih Tzu",
        "name_en": "Shih Tzu",
        "origin": "China/Tibet",
        "size": "small",
        "weight_range": "4-7,5 kg",
        "life_expectancy": "10-16 anos",
        "temperament": ["afetivo", "brincalhão", "leal", "extrovertido", "amigável", "gentil"],
        "energy_level": 2,
        "grooming_level": 5,
        "health_issues": ["problemas oculares", "problemas respiratórios (braquicefálico)", "displasia de quadril", "problemas renais", "hipotireoidismo"],
        "exercise_needs": "20-30 minutos de exercício leve por dia. Brincadeiras internas são suficientes. Evitar exercícios intensos no calor devido aos problemas respiratórios.",
        "feeding_guide": "Adultos: 100-150g de ração premium para raças pequenas por dia em 2 refeições. Atenção à qualidade da alimentação para manutenção da pelagem.",
        "care_tips": ["Escovação diária obrigatória", "Visitas regulares ao groomer", "Limpar ao redor dos olhos diariamente", "Manter fresco no verão"],
        "ideal_environment": "Perfeito para apartamentos. Cão de companhia por excelência. Adapta-se a qualquer ambiente desde que tenha atenção e carinho do tutor.",
        "description": "O Shih Tzu, cujo nome significa 'cão leão' em mandarim, foi criado como cão de companhia para a realeza chinesa. É um animal afetivo e sociável que vive para estar com as pessoas. Sua pelagem longa e luxuosa exige cuidados diários, mas sua personalidade encantadora faz tudo valer a pena.",
    },
    {
        "species": "dog",
        "name": "Maltês",
        "name_en": "Maltese",
        "origin": "Malta",
        "size": "small",
        "weight_range": "2-4 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["gentil", "afetivo", "brincalhão", "responsivo", "confiante", "inteligente"],
        "energy_level": 3,
        "grooming_level": 5,
        "health_issues": ["problemas dentários", "hipoglicemia (filhotes)", "luxação de patela", "shunt portossistêmico", "problemas respiratórios"],
        "exercise_needs": "20-30 minutos de exercício leve por dia. Brincadeiras internas são ideais. Apesar de pequeno, é bastante ativo e gosta de brincar.",
        "feeding_guide": "Adultos: 70-120g de ração premium para raças pequenas por dia em 2-3 refeições. Cuidado com hipoglicemia em filhotes.",
        "care_tips": ["Escovação diária para manter o pelo branco", "Limpeza ao redor dos olhos para evitar manchas", "Cuidados dentários regulares", "Proteção contra o frio"],
        "ideal_environment": "Perfeito para apartamentos. Cão de colo e companhia por excelência. Adora estar com pessoas e não suporta bem a solidão.",
        "description": "O Maltês é uma das raças mais antigas do mundo, apreciado por sua beleza e personalidade doce. Sua pelagem branca e sedosa é sua marca registrada. Apesar do tamanho minúsculo, é surpreendentemente robusto e cheio de vida. Ótimo para pessoas que buscam um companheiro afetuoso.",
    },
    {
        "species": "dog",
        "name": "Cocker Spaniel Inglês",
        "name_en": "English Cocker Spaniel",
        "origin": "Reino Unido",
        "size": "medium",
        "weight_range": "13-14,5 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["alegre", "afetuoso", "ativo", "gentil", "sociável", "obediente"],
        "energy_level": 4,
        "grooming_level": 4,
        "health_issues": ["problemas oculares (cataratas, glaucoma)", "displasia de quadril", "infecções de ouvido", "hipotireoidismo"],
        "exercise_needs": "1-2 horas de exercício diário. Adora explorar ao ar livre e brincar. Foi criado para caçar, então tem muita energia e resistência.",
        "feeding_guide": "Adultos: 200-280g de ração premium por dia em 2 refeições. Monitorar peso e não superalimentar.",
        "care_tips": ["Limpeza semanal das orelhas (propenso a infecções)", "Escovação 2-3 vezes por semana", "Tosquia periódica profissional", "Exercício diário regular"],
        "ideal_environment": "Adapta-se a apartamentos com exercício adequado, mas prefere casas com quintal. Adora a família e se dá bem com crianças.",
        "description": "O Cocker Spaniel Inglês é uma raça alegre e afetiva, famosa por suas orelhas longas e sedosas e olhos expressivos. Originalmente criado para caça, hoje é principalmente um cão de família. É ativo, brincalhão e tem um coração enorme para dar amor.",
    },
    {
        "species": "dog",
        "name": "Dálmata",
        "name_en": "Dalmatian",
        "origin": "Croácia",
        "size": "large",
        "weight_range": "20-32 kg",
        "life_expectancy": "11-13 anos",
        "temperament": ["ativo", "amigável", "inteligente", "independente", "energético", "leal"],
        "energy_level": 5,
        "grooming_level": 2,
        "health_issues": ["surdez (10-12% são surdos)", "urolitíase (pedras nos rins)", "alergias de pele", "displasia de quadril"],
        "exercise_needs": "Necessita de 2+ horas de exercício intenso diário. É incansável e precisa de muito espaço para se movimentar. Ideal para corredores e pessoas muito ativas.",
        "feeding_guide": "Adultos: 300-400g de ração premium por dia em 2 refeições. Dieta com baixo teor de purinas para prevenir pedras nos rins. Muita água é essencial.",
        "care_tips": ["Exercício intenso diário obrigatório", "Escovação semanal", "Manter sempre hidratado", "Teste de audição em filhotes"],
        "ideal_environment": "Não recomendado para apartamentos. Precisa de quintal grande ou acesso fácil a áreas amplas. Família muito ativa é essencial para esta raça.",
        "description": "O Dálmata é facilmente reconhecível por seus pontos pretos ou marrons sobre fundo branco. É uma raça de alto nível de energia que precisa de exercício intenso e consistente. Leal e protetor, é um excelente companheiro para famílias ativas que podem atender suas necessidades energéticas.",
    },
    {
        "species": "dog",
        "name": "Husky Siberiano",
        "name_en": "Siberian Husky",
        "origin": "Sibéria, Rússia",
        "size": "medium",
        "weight_range": "16-27 kg",
        "life_expectancy": "12-14 anos",
        "temperament": ["amigável", "gentil", "alerta", "extrovertido", "inteligente", "espirituoso"],
        "energy_level": 5,
        "grooming_level": 3,
        "health_issues": ["displasia de quadril", "problemas oculares (cataratas, distrofia corneal)", "hipotireoidismo"],
        "exercise_needs": "Necessita de 2+ horas de exercício intenso diário. Criado para correr longas distâncias. Ideal para corredores. Pode escapar de cercas se entediado.",
        "feeding_guide": "Adultos: 250-350g de ração premium por dia em 2 refeições. São conhecidos por comer pouco para o tamanho. Monitorar peso.",
        "care_tips": ["Escovação frequente especialmente na muda", "Nunca deixar solto sem supervisão", "Ambiente fresco é fundamental", "Atividade mental e física intensas"],
        "ideal_environment": "Prefere climas frios. Não recomendado para apartamentos nem para climas muito quentes. Precisa de quintal cercado seguro e muita atividade.",
        "description": "O Husky Siberiano é uma raça de trabalho criada para puxar trenós em temperaturas extremamente baixas. Seu temperamento amigável e olhos penetrantes fazem dele um cão muito admirado. É independente e pode ser teimoso, necessitando de um tutor experiente e comprometido.",
    },
    {
        "species": "dog",
        "name": "Pinscher",
        "name_en": "Miniature Pinscher",
        "origin": "Alemanha",
        "size": "small",
        "weight_range": "4-6 kg",
        "life_expectancy": "12-16 anos",
        "temperament": ["energético", "alerta", "corajoso", "orgulhoso", "leal", "vivaz"],
        "energy_level": 4,
        "grooming_level": 1,
        "health_issues": ["luxação de patela", "problemas oculares", "problemas cardíacos", "síndrome de Legg-Calvé-Perthes"],
        "exercise_needs": "30-45 minutos de exercício diário. Apesar do tamanho, é muito ativo e precisa se exercitar. Brincadeiras intensas em casa também ajudam.",
        "feeding_guide": "Adultos: 100-150g de ração premium para raças pequenas por dia em 2-3 refeições pequenas. Evitar hipoglicemia em filhotes.",
        "care_tips": ["Escovação semanal simples", "Proteger do frio com roupinhas", "Exercício diário", "Socialização desde filhote para reduzir agressividade"],
        "ideal_environment": "Ótimo para apartamentos. Não tolera frio. O 'rei dos brinquedos' como é chamado, tem atitude de cão grande em corpo pequeno.",
        "description": "O Pinscher Miniatura é um cão compacto e elegante com enorme personalidade. Apesar do tamanho diminuto, é arrojado e corajoso. Sua pelagem curta e brilhante requer poucos cuidados, mas sua energia e vivacidade exigem atenção diária.",
    },
    {
        "species": "dog",
        "name": "Lhasa Apso",
        "name_en": "Lhasa Apso",
        "origin": "Tibet",
        "size": "small",
        "weight_range": "5-8 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["assertivo", "inteligente", "brincalhão", "devotado", "desconfiado com estranhos", "independente"],
        "energy_level": 2,
        "grooming_level": 5,
        "health_issues": ["problemas renais", "displasia de quadril", "problemas oculares", "problemas de pele"],
        "exercise_needs": "30 minutos de exercício leve diário. Caminhadas curtas e brincadeiras internas são suficientes para esta raça.",
        "feeding_guide": "Adultos: 100-150g de ração premium por dia em 2 refeições. Atenção à saúde renal com dieta de qualidade.",
        "care_tips": ["Escovação diária obrigatória", "Tosquia profissional regular", "Limpeza dos olhos", "Banho mensal"],
        "ideal_environment": "Perfeito para apartamentos. Originalmente guardião de mosteiros tibetanos, é desconfiado com estranhos mas extremamente leal à família.",
        "description": "O Lhasa Apso é uma raça antiga originária do Tibet, onde era guardião de templos e palácios. Apesar de pequeno, tem personalidade forte e independente. Sua pelagem longa e densa requer cuidados intensos, mas sua lealdade e caráter único recompensam o esforço.",
    },
    {
        "species": "dog",
        "name": "Bichon Frisé",
        "name_en": "Bichon Frisé",
        "origin": "França/Bélgica",
        "size": "small",
        "weight_range": "5-10 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["alegre", "gentil", "brincalhão", "sensitivo", "afetivo", "sociável"],
        "energy_level": 3,
        "grooming_level": 4,
        "health_issues": ["alergias de pele", "problemas oculares", "problemas dentários", "luxação de patela"],
        "exercise_needs": "30-45 minutos de exercício leve a moderado diário. Brincadeiras e caminhadas curtas atendem bem suas necessidades.",
        "feeding_guide": "Adultos: 100-150g de ração premium para raças pequenas por dia em 2 refeições. Atenção a alergias alimentares.",
        "care_tips": ["Tosquia profissional a cada 4-6 semanas", "Escovação frequente", "Hipoalergênico - bom para alérgicos", "Atenção às alergias de pele"],
        "ideal_environment": "Ótimo para apartamentos. Extremamente sociável e não suporta ficar sozinho por muito tempo. Perfeito para famílias e idosos.",
        "description": "O Bichon Frisé é um cão alegre e afetivo com uma pelagem branca e encaracolada característica. Hipoalergênico, é uma ótima opção para pessoas com alergias. Adora atenção e é excelente com crianças e outros animais. Sua natureza alegre ilumina qualquer ambiente.",
    },
    {
        "species": "dog",
        "name": "Border Collie",
        "name_en": "Border Collie",
        "origin": "Reino Unido",
        "size": "medium",
        "weight_range": "14-20 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["inteligente", "energético", "responsivo", "alertas", "resistente", "atento"],
        "energy_level": 5,
        "grooming_level": 3,
        "health_issues": ["displasia de quadril", "anomalia do olho do collie", "epilepsia", "sensibilidade à MDR1"],
        "exercise_needs": "2+ horas de exercício intenso diário mais estimulação mental constante. É considerado o cão mais inteligente do mundo e precisa de trabalho mental.",
        "feeding_guide": "Adultos: 300-400g de ração premium por dia em 2 refeições. Alta atividade exige alimentação de qualidade. Monitorar peso.",
        "care_tips": ["Exercício e estimulação mental diários obrigatórios", "Treinamento constante", "Escovação 2-3 vezes por semana", "Não recomendado para donos sedentários"],
        "ideal_environment": "Não recomendado para apartamentos. Precisa de espaço amplo e de muita atividade. Fazendas e propriedades rurais são ideais. Família muito ativa é essencial.",
        "description": "O Border Collie é amplamente considerado o cão mais inteligente do mundo. Criado para pastorear ovelhas, tem um nível de energia e inteligência que exige estimulação constante. Em mãos erradas pode desenvolver comportamentos destrutivos. Em mãos certas, é um parceiro incomparável.",
    },
    {
        "species": "dog",
        "name": "Boxer",
        "name_en": "Boxer",
        "origin": "Alemanha",
        "size": "large",
        "weight_range": "25-35 kg",
        "life_expectancy": "10-12 anos",
        "temperament": ["brincalhão", "energético", "leal", "protetor", "inteligente", "carinhoso"],
        "energy_level": 4,
        "grooming_level": 1,
        "health_issues": ["cardiomiopatia dilatada", "estenose aórtica", "câncer", "displasia de quadril", "problemas respiratórios (braquicefálico)"],
        "exercise_needs": "1-2 horas de exercício moderado a intenso diário. É uma raça muito ativa e brincalhona. Precisa de espaço para correr e brincar.",
        "feeding_guide": "Adultos: 350-450g de ração de alta qualidade por dia em 2 refeições. Evitar exercício imediatamente após alimentação.",
        "care_tips": ["Escovação semanal simples", "Limpeza das dobras faciais", "Evitar calor excessivo", "Socialização e treinamento desde filhote"],
        "ideal_environment": "Prefere casas com quintal. Pode se adaptar a apartamentos grandes com exercício adequado. Família ativa que possa brincar muito é o ideal.",
        "description": "O Boxer é um cão musculoso e elegante com um coração enorme. É conhecido por ser eternamente jovem em espírito, mantendo o comportamento brincalhão mesmo na idade adulta. Extremamente leal e protetor da família, mas gentil e carinhoso com os que ama.",
    },
    {
        "species": "dog",
        "name": "Dobermann",
        "name_en": "Doberman Pinscher",
        "origin": "Alemanha",
        "size": "large",
        "weight_range": "32-45 kg",
        "life_expectancy": "10-13 anos",
        "temperament": ["leal", "obediente", "corajoso", "confiante", "energético", "inteligente"],
        "energy_level": 4,
        "grooming_level": 1,
        "health_issues": ["cardiomiopatia dilatada", "doença de Von Willebrand", "hipotireoidismo", "displasia de quadril"],
        "exercise_needs": "1-2 horas de exercício intenso diário. É uma raça atlética que precisa de trabalho mental e físico para ser feliz.",
        "feeding_guide": "Adultos: 400-500g de ração premium por dia em 2 refeições. Ração de alta qualidade para raças ativas e de trabalho.",
        "care_tips": ["Treinamento e socialização precoces são essenciais", "Exercício intenso diário", "Escovação simples semanal", "Exames cardíacos regulares"],
        "ideal_environment": "Prefere casas com quintal. Necessita de tutor experiente e firme. Com socialização adequada é um cão de família excelente e protetor.",
        "description": "O Dobermann foi criado no século XIX para ser o cão de guarda perfeito. É inteligente, leal e corajoso. Com o treinamento adequado, torna-se um companheiro dócil e afetuoso. Sua aparência elegante e postura imponente o fazem um guardião natural.",
    },
    {
        "species": "dog",
        "name": "São Bernardo",
        "name_en": "Saint Bernard",
        "origin": "Suíça",
        "size": "giant",
        "weight_range": "65-120 kg",
        "life_expectancy": "8-10 anos",
        "temperament": ["gentil", "amigável", "calmo", "paciente", "obediente", "caloroso"],
        "energy_level": 2,
        "grooming_level": 3,
        "health_issues": ["displasia de quadril", "displasia de cotovelo", "torção gástrica", "osteossarcoma", "cardiomiopatia"],
        "exercise_needs": "30-60 minutos de exercício moderado diário. Não suporta calor. Evitar exercícios intensos em dias quentes.",
        "feeding_guide": "Adultos: 600-900g de ração premium para raças gigantes por dia em 3 refeições. Ração específica para raças gigantes para controle do crescimento.",
        "care_tips": ["Escovação 2-3 vezes por semana", "Manter em ambiente fresco", "Controlar a baba (frequente)", "Exames ortopédicos regulares"],
        "ideal_environment": "Necessita de espaço amplo. Não tolera calor. Ideal para casas grandes em climas frios. Apesar do tamanho, é surpreendentemente calmo e gentil.",
        "description": "O São Bernardo é o gigante gentil dos cães, famoso por resgatar pessoas perdidas nas Alpes Suíças. Apesar de seu tamanho impressionante, é um cão calmo, paciente e extremamente carinhoso. É ótimo com crianças e outros animais, sendo um companheiro leal e protetor.",
    },
    {
        "species": "dog",
        "name": "Chow Chow",
        "name_en": "Chow Chow",
        "origin": "China",
        "size": "medium",
        "weight_range": "20-32 kg",
        "life_expectancy": "8-12 anos",
        "temperament": ["independente", "leal", "quieto", "distante com estranhos", "digno", "sério"],
        "energy_level": 2,
        "grooming_level": 4,
        "health_issues": ["displasia de quadril", "entrópio", "problemas de tireoide", "diabetes", "pênfigo"],
        "exercise_needs": "20-30 minutos de exercício moderado diário. Não tolera calor excessivo. Prefere atividades tranquilas a corridas intensas.",
        "feeding_guide": "Adultos: 250-350g de ração premium por dia em 2 refeições. Atenção à saúde dental e ao peso.",
        "care_tips": ["Escovação frequente especialmente no undercoat", "Manter em ambiente fresco", "Socialização extensiva desde filhote", "Limpeza das dobras faciais"],
        "ideal_environment": "Adapta-se a apartamentos com exercício leve. Prefere climas mais frios. Não é um cão para todos - requer um tutor paciente e compreensivo.",
        "description": "O Chow Chow é uma raça antiga da China, reconhecível por sua língua azul-preta e pelagem abundante. É conhecido por seu temperamento independente e distante, sendo muito leal ao seu tutor mas reservado com estranhos. Não é o cão mais efusivo, mas sua lealdade é inabalável.",
    },
    {
        "species": "dog",
        "name": "Dachshund (Bassê)",
        "name_en": "Dachshund",
        "origin": "Alemanha",
        "size": "small",
        "weight_range": "3-9 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["corajoso", "vivaz", "devotado", "brincalhão", "teimoso", "curioso"],
        "energy_level": 3,
        "grooming_level": 2,
        "health_issues": ["doença do disco intervertebral", "obesidade", "diabetes", "epilepsia", "problemas oculares"],
        "exercise_needs": "30-45 minutos de exercício leve diário. Evitar pulos altos e escadas que sobrecarregam a coluna. Caminhadas planas são ideais.",
        "feeding_guide": "Adultos: 150-220g de ração premium por dia em 2 refeições. Muito propenso à obesidade que agrava problemas de coluna.",
        "care_tips": ["Controlar rigorosamente o peso", "Evitar escadas e pulos", "Usar rampas em vez de escadas", "Escovação conforme tipo de pelagem"],
        "ideal_environment": "Ótimo para apartamentos sem escadas ou com rampas. Apesar do tamanho, tem personalidade forte. Não deixe subir/descer de lugares altos.",
        "description": "O Dachshund, popularmente chamado de Bassê no Brasil, é um cão alongado e baixo criado para caçar animais em tocas. Tem uma personalidade corajosa e teimosa que não combina com seu tamanho pequeno. É muito afetivo com a família mas pode ser desconfiante com estranhos.",
    },
    {
        "species": "dog",
        "name": "Schnauzer",
        "name_en": "Schnauzer",
        "origin": "Alemanha",
        "size": "small",
        "weight_range": "4-9 kg (miniatura)",
        "life_expectancy": "12-14 anos",
        "temperament": ["espirituoso", "alerta", "obediente", "leal", "inteligente", "ativo"],
        "energy_level": 4,
        "grooming_level": 3,
        "health_issues": ["hiperlipidemia", "pancreatite", "urolitíase", "problemas oculares"],
        "exercise_needs": "45-60 minutos de exercício moderado a intenso diário. É uma raça ativa que precisa de estimulação física e mental.",
        "feeding_guide": "Adultos: 100-150g (miniatura) a 300-400g (padrão) de ração premium por dia em 2 refeições. Atenção à dieta para prevenir hiperlipidemia.",
        "care_tips": ["Tosquia profissional a cada 6-8 semanas", "Escovação 2-3 vezes por semana", "Limpeza da barba após refeições", "Exercício diário regular"],
        "ideal_environment": "O Schnauzer Miniatura é ótimo para apartamentos. O Schnauzer Padrão e Gigante precisam de mais espaço. Todos são ativos e precisam de exercício.",
        "description": "O Schnauzer vem em três tamanhos: miniatura, padrão e gigante, todos com o característico bigode e sobrancelhas. É uma raça versátil, utilizada como cão de companhia, guarda e até caça. Inteligente e leal, é fácil de treinar e se adapta bem à vida em família.",
    },
    {
        "species": "dog",
        "name": "Akita",
        "name_en": "Akita",
        "origin": "Japão",
        "size": "large",
        "weight_range": "32-59 kg",
        "life_expectancy": "10-13 anos",
        "temperament": ["corajoso", "leal", "digno", "receptivo", "composto", "silencioso"],
        "energy_level": 3,
        "grooming_level": 3,
        "health_issues": ["displasia de quadril", "hipotireoidismo", "sensibilidade a medicamentos", "pseudoparalisia", "microse ocular"],
        "exercise_needs": "1-2 horas de exercício moderado diário. Não é tão exigente quanto outras raças grandes, mas precisa de caminhadas regulares.",
        "feeding_guide": "Adultos: 400-600g de ração premium por dia em 2 refeições. Ração de alta qualidade para raças grandes e ativas.",
        "care_tips": ["Socialização extensiva e precoce", "Escovação frequente especialmente na muda", "Não recomendado com outros cães", "Tutor experiente necessário"],
        "ideal_environment": "Prefere casas com quintal. Não é recomendado para famílias com outros animais. Precisa de um tutor experiente e firme.",
        "description": "O Akita é um símbolo nacional do Japão, representando saúde, felicidade e longevidade. É famoso pela história de Hachiko, o cão mais leal do mundo. Silencioso e digno, é extremamente leal ao seu tutor mas pode ser territorial e agressivo com outros cães.",
    },
    {
        "species": "dog",
        "name": "Pitbull (APBT)",
        "name_en": "American Pit Bull Terrier",
        "origin": "Estados Unidos",
        "size": "medium",
        "weight_range": "14-27 kg",
        "life_expectancy": "12-14 anos",
        "temperament": ["corajoso", "confiante", "leal", "brincalhão", "afetuoso com família", "inteligente"],
        "energy_level": 5,
        "grooming_level": 1,
        "health_issues": ["displasia de quadril", "alergias de pele", "hipotireoidismo", "doenças cardíacas", "displasia de cotovelo"],
        "exercise_needs": "1-2 horas de exercício intenso diário. É muito musculoso e ativo. Precisar de atividade física e mental para não desenvolver comportamentos destrutivos.",
        "feeding_guide": "Adultos: 300-450g de ração premium para raças ativas por dia em 2 refeições. Dieta de alta proteína para manutenção muscular.",
        "care_tips": ["Socialização precoce e extensa é fundamental", "Treinamento de obediência desde filhote", "Exercício intenso diário", "Escovação simples semanal"],
        "ideal_environment": "Prefere casas com quintal. Pode adaptar-se a apartamentos com exercício intenso. Precisa de tutor comprometido e experiente. É um cão extremamente afetuoso com humanos.",
        "description": "O American Pit Bull Terrier é frequentemente mal compreendido por sua reputação. Na realidade, é um cão extremamente afetuoso e leal com humanos, sendo apelidado de 'babá' por sua gentileza com crianças. Requer socialização precoce e treinamento consistente de um tutor responsável.",
    },
    {
        "species": "dog",
        "name": "French Bulldog",
        "name_en": "French Bulldog",
        "origin": "França/Reino Unido",
        "size": "small",
        "weight_range": "8-13 kg",
        "life_expectancy": "10-12 anos",
        "temperament": ["afetuoso", "brincalhão", "alerta", "adaptável", "sociável", "paciente"],
        "energy_level": 2,
        "grooming_level": 1,
        "health_issues": ["síndrome braquicefálica", "displasia de quadril", "problemas de pele nas dobras", "luxação de patela", "problemas cardíacos"],
        "exercise_needs": "20-30 minutos de exercício leve diário. Não tolera calor nem exercícios intensos. Brincadeiras internas são ideais.",
        "feeding_guide": "Adultos: 200-250g de ração premium por dia em 2 refeições. Propenso a ganho de peso. Manter dieta controlada.",
        "care_tips": ["Limpar dobras faciais diariamente", "Manter em ambiente climatizado", "Evitar exercícios intensos e calor", "Limpeza das orelhas semanal"],
        "ideal_environment": "Perfeito para apartamentos. Um dos cães mais adaptáveis para vida urbana. Adora atenção e companhia humana.",
        "description": "O Bulldog Francês é um dos cães mais populares do mundo, especialmente em ambientes urbanos. Suas orelhas em forma de morcego e expressão pensativa o tornam irresistível. É carinhoso, adaptável e relativamente calmo, sendo ideal para apartamentos e vida na cidade.",
    },
    {
        "species": "dog",
        "name": "Pug",
        "name_en": "Pug",
        "origin": "China",
        "size": "small",
        "weight_range": "6-8 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["encantador", "travesso", "amoroso", "obstinado", "sociável", "estável"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["síndrome braquicefálica", "obesidade", "problemas oculares", "encefalite do Pug", "displasia de quadril"],
        "exercise_needs": "20-30 minutos de exercício leve. Evitar exercícios intensos e calor. Brincadeiras curtas e caminhadas tranquilas são ideais.",
        "feeding_guide": "Adultos: 150-200g de ração premium por dia em 2 refeições. Extremamente propenso à obesidade. Controle rígido das porções.",
        "care_tips": ["Limpar as rugas faciais diariamente", "Limpar ao redor dos olhos", "Manter em ambiente fresco", "Controlar rigorosamente o peso"],
        "ideal_environment": "Perfeito para apartamentos. Cão de companhia ideal para idosos e pessoas menos ativas. Adora colo e atenção constante.",
        "description": "O Pug é um cão pequeno com face achatada e expressão cômica que conquistou o coração de muitos. Originário da China imperial, foi cão dos reis. Muito afetivo e engraçado, é um companheiro de vida excelente que vive para a família.",
    },
    {
        "species": "dog",
        "name": "Weimaraner",
        "name_en": "Weimaraner",
        "origin": "Alemanha",
        "size": "large",
        "weight_range": "25-40 kg",
        "life_expectancy": "10-13 anos",
        "temperament": ["amistoso", "obediente", "alerta", "corajoso", "energético", "inteligente"],
        "energy_level": 5,
        "grooming_level": 1,
        "health_issues": ["displasia de quadril", "torção gástrica", "entrópio", "displasia de cotovelo", "problemas de pele"],
        "exercise_needs": "2+ horas de exercício intenso diário. É incansável e precisa de espaço amplo. Correr, nadar e caçar são atividades ideais.",
        "feeding_guide": "Adultos: 350-500g de ração premium para raças ativas por dia em 2-3 refeições. Evitar exercício após alimentação.",
        "care_tips": ["Exercício intenso diário obrigatório", "Treinamento de obediência", "Escovação simples semanal", "Não pode ficar sozinho por muito tempo"],
        "ideal_environment": "Necessita de espaço amplo e família muito ativa. Não recomendado para apartamentos. Ideal para propriedades rurais ou casas com quintal grande.",
        "description": "O Weimaraner é um cão de caça alemão elegante e atlético, também chamado de 'fantasma prateado' por sua pelagem cinza brilhante. É extremamente energético e precisa de um tutor muito ativo. Inteligente e leal, pode ser um excelente cão de família quando suas necessidades são atendidas.",
    },
    {
        "species": "dog",
        "name": "Vizsla",
        "name_en": "Vizsla",
        "origin": "Hungria",
        "size": "medium",
        "weight_range": "18-29 kg",
        "life_expectancy": "12-14 anos",
        "temperament": ["afetuoso", "energético", "gentil", "leal", "inteligente", "vivo"],
        "energy_level": 5,
        "grooming_level": 1,
        "health_issues": ["displasia de quadril", "epilepsia", "linfoma", "hemangiosarcoma", "hipotireoidismo"],
        "exercise_needs": "2+ horas de exercício intenso diário. Cão de caça que precisa correr, nadar e explorar. Ideal para corredores e ciclistas.",
        "feeding_guide": "Adultos: 300-400g de ração premium para raças ativas por dia em 2 refeições. Alta proteína para suportar o nível de atividade.",
        "care_tips": ["Exercício intenso diário", "Socialização precoce", "Treinamento gentil e positivo", "Escovação simples semanal"],
        "ideal_environment": "Casas com quintal grande. Família muito ativa é essencial. Chama-se de 'velcro dog' por ficar sempre grudado ao tutor.",
        "description": "O Vizsla é um cão de caça húngaro elegante e multifuncional. Extremamente afetuoso com a família, é conhecido como o 'cão velcro' por sua necessidade de estar sempre perto dos tutores. Muito energético, precisa de tutores que possam atender seu alto nível de atividade.",
    },
    {
        "species": "dog",
        "name": "Australian Shepherd",
        "name_en": "Australian Shepherd",
        "origin": "Estados Unidos",
        "size": "medium",
        "weight_range": "16-32 kg",
        "life_expectancy": "13-15 anos",
        "temperament": ["inteligente", "ativo", "protetor", "leal", "brincalhão", "versátil"],
        "energy_level": 5,
        "grooming_level": 3,
        "health_issues": ["displasia de quadril", "anomalia do olho do collie", "epilepsia", "MDR1 (sensibilidade a medicamentos)"],
        "exercise_needs": "2+ horas de exercício intenso diário mais estimulação mental. Criado para pastorear, tem energia inesgotável.",
        "feeding_guide": "Adultos: 300-400g de ração premium por dia em 2 refeições. Alta qualidade para suportar o nível de atividade.",
        "care_tips": ["Exercício e estimulação mental diários obrigatórios", "Escovação 2-3 vezes por semana", "Treinamento regular", "Não recomendado para donos sedentários"],
        "ideal_environment": "Precisa de espaço amplo e família muito ativa. Não recomendado para apartamentos. Ideal para propriedades com espaço.",
        "description": "O Australian Shepherd (Aussie) é um cão de pastoreio americano incansável e extremamente inteligente. Apesar do nome, foi desenvolvido nos Estados Unidos. É um atleta nato que se destaca em agility, frisbee e outras atividades. Precisa de trabalho constante para ser feliz.",
    },
    {
        "species": "dog",
        "name": "Samoieda",
        "name_en": "Samoyed",
        "origin": "Sibéria, Rússia",
        "size": "medium",
        "weight_range": "16-30 kg",
        "life_expectancy": "12-14 anos",
        "temperament": ["amigável", "gentil", "adaptável", "alerta", "brincalhão", "sociável"],
        "energy_level": 4,
        "grooming_level": 5,
        "health_issues": ["displasia de quadril", "glaucoma", "hipotireoidismo", "diabetes", "síndrome de Fanconi"],
        "exercise_needs": "1-2 horas de exercício moderado a intenso diário. Adora atividades ao ar livre especialmente em climas frios.",
        "feeding_guide": "Adultos: 250-350g de ração premium por dia em 2 refeições. Atenção à qualidade para manter a pelagem brilhante.",
        "care_tips": ["Escovação diária especialmente na muda", "Manter em ambiente fresco", "Banho mensal ou quando necessário", "Pelagem branca requer cuidados especiais"],
        "ideal_environment": "Prefere climas frios. Não recomendado para regiões muito quentes. Adora família e atividades ao ar livre.",
        "description": "O Samoieda é facilmente reconhecível por sua densa pelagem branca e o característico 'sorriso samoyedo'. Criado pelos nômades siberianos para puxar trenós e pastorear renas, é um cão de trabalho alegre e amigável. Sua natureza gentil o torna excelente com crianças.",
    },
    {
        "species": "dog",
        "name": "Malinois Belga",
        "name_en": "Belgian Malinois",
        "origin": "Bélgica",
        "size": "medium",
        "weight_range": "18-30 kg",
        "life_expectancy": "14-16 anos",
        "temperament": ["inteligente", "obediente", "confiante", "vigilante", "protetor", "intenso"],
        "energy_level": 5,
        "grooming_level": 2,
        "health_issues": ["displasia de quadril", "displasia de cotovelo", "epilepsia", "problemas oculares"],
        "exercise_needs": "3+ horas de exercício muito intenso diário mais trabalho mental. É utilizado por forças especiais do mundo inteiro. Raça extremamente exigente.",
        "feeding_guide": "Adultos: 350-450g de ração premium para raças ativas por dia em 2 refeições. Alta proteína para o nível de atividade extremo.",
        "care_tips": ["Exercício extremamente intenso diário", "Trabalho/esporte canino é essencial", "Escovação semanal", "Não recomendado para donos iniciantes"],
        "ideal_environment": "Não recomendado para apartamentos nem para donos sem experiência. Precisa de trabalho e propósito. Ideal para K9, agility, proteção.",
        "description": "O Malinois Belga é um dos cães de trabalho mais exigentes e capazes do mundo. Utilizado por forças especiais, polícias e exércitos do mundo todo. É extremamente inteligente e leal, mas requer um tutor muito experiente. Não é recomendado como animal de companhia por iniciantes.",
    },
    {
        "species": "dog",
        "name": "Cavalier King Charles Spaniel",
        "name_en": "Cavalier King Charles Spaniel",
        "origin": "Reino Unido",
        "size": "small",
        "weight_range": "5,4-8,2 kg",
        "life_expectancy": "9-14 anos",
        "temperament": ["afetuoso", "gentil", "gracioso", "paciente", "brincalhão", "adaptável"],
        "energy_level": 3,
        "grooming_level": 3,
        "health_issues": ["síndrome de Chiari-malformação", "doença valvar mitral", "displasia de quadril", "problemas oculares"],
        "exercise_needs": "45-60 minutos de exercício leve a moderado diário. Caminhadas tranquilas e brincadeiras atendem bem suas necessidades.",
        "feeding_guide": "Adultos: 150-200g de ração premium por dia em 2 refeições. Atenção à saúde cardíaca com dieta de qualidade.",
        "care_tips": ["Escovação 3-4 vezes por semana", "Limpeza das orelhas semanal", "Exames cardíacos regulares", "Socialização desde filhote"],
        "ideal_environment": "Ótimo para apartamentos. Um dos cães mais adaptáveis. Ama pessoas e se dá bem com crianças, idosos e outros animais.",
        "description": "O Cavalier King Charles Spaniel é considerado o cão de companhia perfeito por muitos. Criado para ser companheiro da realeza inglesa, é extremamente afetuoso e gentil. Seu olhar doce e personalidade carinhosa conquistam qualquer um. É um dos cães mais adaptáveis de todas as raças.",
    },
    {
        "species": "dog",
        "name": "Spitz Alemão (Lulu da Pomerânia)",
        "name_en": "Pomeranian",
        "origin": "Alemanha/Polônia",
        "size": "small",
        "weight_range": "1,8-3,5 kg",
        "life_expectancy": "12-16 anos",
        "temperament": ["vivaz", "inteligente", "extrovertido", "ativo", "sociável", "corajoso"],
        "energy_level": 3,
        "grooming_level": 4,
        "health_issues": ["luxação de patela", "colapso traqueal", "problemas dentários", "calvície do Pomerânio (BOAS)"],
        "exercise_needs": "20-30 minutos de exercício leve a moderado diário. Brincadeiras internas e caminhadas curtas são suficientes.",
        "feeding_guide": "Adultos: 80-120g de ração premium para raças muito pequenas por dia em 2-3 refeições. Cuidado com hipoglicemia.",
        "care_tips": ["Escovação diária para evitar nós", "Tosquia profissional regular", "Cuidados dentários frequentes", "Proteger do calor excessivo"],
        "ideal_environment": "Perfeito para apartamentos. Apesar do tamanho, latido frequente pode ser problema em condomínios. Treinamento de latido recomendado.",
        "description": "O Spitz Alemão, chamado de Lulu da Pomerânia no Brasil, é um cão pequeno e fofo com personalidade gigante. Sua pelagem dupla e abundante e a cauda enrolada sobre as costas são marcas registradas. É esperto, vivaz e absolutamente adorável.",
    },
    {
        "species": "dog",
        "name": "Shar Pei",
        "name_en": "Shar Pei",
        "origin": "China",
        "size": "medium",
        "weight_range": "18-29 kg",
        "life_expectancy": "8-12 anos",
        "temperament": ["leal", "independente", "calmo", "dedicado", "desconfiado com estranhos", "sério"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["febre do Shar Pei", "problemas oculares (entrópio)", "infecções nas dobras", "problemas renais", "alergias"],
        "exercise_needs": "30-45 minutos de exercício moderado diário. Não tolera calor excessivo. Atividade física regular mas não intensa.",
        "feeding_guide": "Adultos: 250-350g de ração premium por dia em 2 refeições. Dieta de alta qualidade para minimizar alergias.",
        "care_tips": ["Limpar as dobras diariamente para evitar infecções", "Socialização extensiva desde filhote", "Manter em ambiente fresco", "Exames oculares regulares"],
        "ideal_environment": "Adapta-se a apartamentos com exercício adequado. Prefere climas mais frescos. Não é sociável por natureza com outros cães.",
        "description": "O Shar Pei é facilmente reconhecível por suas abundantes dobras de pele e focinho semelhante a um hipopótamo. Criado na China antiga como cão de luta e guarda, é independente e reservado. Com socialização adequada, torna-se extremamente leal ao tutor.",
    },
    {
        "species": "dog",
        "name": "Basset Hound",
        "name_en": "Basset Hound",
        "origin": "França/Reino Unido",
        "size": "medium",
        "weight_range": "18-27 kg",
        "life_expectancy": "10-12 anos",
        "temperament": ["terno", "obstinado", "devotado", "gentil", "paciente", "leal"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["infecções de ouvido", "obesidade", "problemas oculares", "problemas de coluna", "displasia de cotovelo"],
        "exercise_needs": "20-30 minutos de exercício leve diário. Caminhadas tranquilas são suficientes. Muito propenso à preguiça e à obesidade.",
        "feeding_guide": "Adultos: 250-350g de ração premium por dia em 2-3 refeições pequenas. Controle rigoroso do peso para proteger a coluna.",
        "care_tips": ["Limpeza das orelhas semanal obrigatória", "Controle de peso rigoroso", "Limpar dobras faciais", "Evitar superfícies muito escorregadias"],
        "ideal_environment": "Adapta-se a apartamentos com passeios regulares. É calmo e não requer muito exercício. Boa opção para tutores menos ativos.",
        "description": "O Basset Hound é um cão de caça francês de pernas curtas e orelhas longas, com um olfato extraordinário. Apesar da aparência melancólica, é um cão gentil e paciente, ótimo com crianças. Tem voz marcante (baio) e pode ser teimoso, mas é extremamente afetuoso.",
    },
    {
        "species": "dog",
        "name": "Jack Russell Terrier",
        "name_en": "Jack Russell Terrier",
        "origin": "Reino Unido",
        "size": "small",
        "weight_range": "5-8 kg",
        "life_expectancy": "13-16 anos",
        "temperament": ["vivo", "enérgico", "corajoso", "inteligente", "independente", "brincalhão"],
        "energy_level": 5,
        "grooming_level": 2,
        "health_issues": ["luxação de patela", "síndrome de Legg-Calvé-Perthes", "problemas oculares", "surdez"],
        "exercise_needs": "1+ hora de exercício intenso diário. Apesar do tamanho, tem energia inesgotável. Precisa de muita atividade para não ficar destrutivo.",
        "feeding_guide": "Adultos: 150-200g de ração premium para raças pequenas por dia em 2 refeições. Manter hidratado durante atividades intensas.",
        "care_tips": ["Exercício intenso diário", "Treinamento de obediência firme", "Ambientes fechados (grande instinto de fuga)", "Estimulação mental"],
        "ideal_environment": "Pode adaptar-se a apartamentos com muito exercício. Quintal cercado é ideal. Não recomendado para tutores sedentários.",
        "description": "O Jack Russell Terrier é uma bomba de energia em corpo pequeno. Criado para caçar raposas, tem instintos de caça muito fortes. É corajoso, inteligente e tremendamente enérgico. Sua personalidade exuberante exige tutores ativos e dedicados ao treinamento.",
    },
    {
        "species": "dog",
        "name": "Cocker Spaniel Americano",
        "name_en": "American Cocker Spaniel",
        "origin": "Estados Unidos",
        "size": "medium",
        "weight_range": "9-14 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["alegre", "gentil", "sociável", "sensível", "afetuoso", "obediente"],
        "energy_level": 3,
        "grooming_level": 5,
        "health_issues": ["problemas oculares", "infecções de ouvido", "displasia de quadril", "hipotireoidismo", "doença renal"],
        "exercise_needs": "45-60 minutos de exercício moderado diário. Caminhadas e brincadeiras ao ar livre atendem suas necessidades.",
        "feeding_guide": "Adultos: 200-250g de ração premium por dia em 2 refeições. Atenção ao peso e saúde dos olhos.",
        "care_tips": ["Tosquia profissional frequente", "Limpeza semanal das orelhas", "Escovação diária da pelagem longa", "Exames oculares regulares"],
        "ideal_environment": "Adapta-se bem a apartamentos e casas. É muito sociável e ama a família. Bom com crianças e outros animais.",
        "description": "O Cocker Spaniel Americano é elegante e carinhoso, com sua característica pelagem longa e sedosa. É uma das raças mais populares nos Estados Unidos. Sua personalidade doce e olhos expressivos conquistam facilmente. É sensível e responde melhor a treinamento positivo e gentil.",
    },
    {
        "species": "dog",
        "name": "Fila Brasileiro",
        "name_en": "Brazilian Mastiff",
        "origin": "Brasil",
        "size": "giant",
        "weight_range": "40-80 kg",
        "life_expectancy": "9-11 anos",
        "temperament": ["determinado", "leal", "corajoso", "obstinado", "protetor", "dócil com família"],
        "energy_level": 3,
        "grooming_level": 2,
        "health_issues": ["displasia de quadril", "displasia de cotovelo", "torção gástrica", "osteossarcoma", "ectrópio"],
        "exercise_needs": "1 hora de exercício moderado diário. Apesar do tamanho, não requer exercício excessivo. Caminhadas regulares são suficientes.",
        "feeding_guide": "Adultos: 600-900g de ração premium para raças gigantes por dia em 2-3 refeições. Nunca exercitar imediatamente após alimentação.",
        "care_tips": ["Socialização precoce e extensiva", "Tutor experiente obrigatório", "Escovação semanal simples", "Exames ortopédicos regulares"],
        "ideal_environment": "Precisa de espaço amplo. Não recomendado para apartamentos nem para tutores inexperientes. É uma raça brasileira com instinto de guarda muito intenso.",
        "description": "O Fila Brasileiro é uma raça nacional de grande porte, desenvolvida no Brasil para guardar fazendas e rastrear escravos fugitivos. Extremamente leal à família, é desconfiante por natureza com estranhos (ojeriza). Requer um tutor experiente e espaço adequado para seu tamanho.",
    },
]

CAT_BREEDS = [
    {
        "species": "cat",
        "name": "Persa",
        "name_en": "Persian",
        "origin": "Irã (antiga Pérsia)",
        "size": "medium",
        "weight_range": "3-7 kg",
        "life_expectancy": "12-17 anos",
        "temperament": ["calmo", "gentil", "quieto", "afetuoso", "dócil", "dignificado"],
        "energy_level": 1,
        "grooming_level": 5,
        "health_issues": ["síndrome braquicefálica", "doença renal policística (PKD)", "cardiomiopatia hipertrófica", "problemas oculares"],
        "exercise_needs": "Exercício leve. Prefere ambientes calmos e não é muito ativo. Brinquedos suaves são suficientes para sua estimulação.",
        "feeding_guide": "Adultos: 50-80g de ração premium para raças longas por dia em 2 refeições. Ração específica com formato de grão para braquicefálicos.",
        "care_tips": ["Escovação diária obrigatória", "Limpeza dos olhos diária", "Banho mensal", "Ambiente calmo sem muita agitação"],
        "ideal_environment": "Perfeito para apartamentos calmos. Não se adapta bem a ambientes barulhentos ou com muita agitação. Ideal para tutores tranquilos.",
        "description": "O Gato Persa é a raça felina mais elegante e majestosa, com sua pelagem longa e luxuosa e face achatada característica. É um gato calmo e dócil que aprecia a quietude e a rotina. Requer cuidados intensos com a pelagem, mas seu temperamento sereno recompensa o esforço.",
    },
    {
        "species": "cat",
        "name": "Maine Coon",
        "name_en": "Maine Coon",
        "origin": "Estados Unidos (Maine)",
        "size": "large",
        "weight_range": "4-10 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["amigável", "brincalhão", "inteligente", "gentil", "sociável", "adaptável"],
        "energy_level": 3,
        "grooming_level": 3,
        "health_issues": ["cardiomiopatia hipertrófica", "displasia de quadril", "deficiência de piruvato quinase", "espinha muscular espinal"],
        "exercise_needs": "Exercício moderado. Gosta de brincar e explorar. Brinquedos interativos e postes de escalada são ideais.",
        "feeding_guide": "Adultos: 80-120g de ração premium para raças grandes por dia em 2-3 refeições. Ração de qualidade para manter a pelagem.",
        "care_tips": ["Escovação 2-3 vezes por semana", "Postes de arranhamento e escalada", "Brinquedos interativos", "Exames cardíacos regulares"],
        "ideal_environment": "Adapta-se bem a apartamentos e casas. É um dos maiores gatos domésticos do mundo. Sociável e se dá bem com cães e crianças.",
        "description": "O Maine Coon é o maior gato doméstico do mundo, com pelagem espessa e cauda longa e abundante. Apesar do tamanho, é gentil e brincalhão, sendo chamado de 'cão dos gatos' por seu comportamento sociável. Adapta-se bem a famílias com crianças e outros animais.",
    },
    {
        "species": "cat",
        "name": "Siamês",
        "name_en": "Siamese",
        "origin": "Tailândia (Sião)",
        "size": "medium",
        "weight_range": "3-5,5 kg",
        "life_expectancy": "15-20 anos",
        "temperament": ["vocal", "afetuoso", "curioso", "inteligente", "social", "exigente"],
        "energy_level": 4,
        "grooming_level": 1,
        "health_issues": ["amiloidose hepática", "cardiomiopatia dilatada", "problemas respiratórios", "neoplasia mamária"],
        "exercise_needs": "Moderado a alto. Muito curioso e ativo, precisa de estimulação mental e física constante. Brinquedos e interação humana são essenciais.",
        "feeding_guide": "Adultos: 50-70g de ração premium por dia em 2-3 refeições. Manter dieta equilibrada para evitar sobrepeso.",
        "care_tips": ["Brinquedos interativos diários", "Muito carinho e atenção", "Não tolera solidão", "Enriquecimento ambiental"],
        "ideal_environment": "Apartamentos são ok, mas precisa de muita interação. É o gato mais vocal do mundo - pode ser muito alto. Ideal para quem está muito em casa.",
        "description": "O Siamês é uma das raças mais antigas e reconhecíveis do mundo, com seus pontos escuros (face, orelhas, patas e cauda) sobre fundo claro e olhos azuis penetrantes. É extremamente vocal e comunicativo, estabelecendo vínculos muito fortes com os tutores. Não gosta de ficar sozinho.",
    },
    {
        "species": "cat",
        "name": "Ragdoll",
        "name_en": "Ragdoll",
        "origin": "Estados Unidos",
        "size": "large",
        "weight_range": "4,5-9 kg",
        "life_expectancy": "12-17 anos",
        "temperament": ["calmo", "dócil", "gentil", "carinhoso", "sociável", "relaxado"],
        "energy_level": 2,
        "grooming_level": 3,
        "health_issues": ["cardiomiopatia hipertrófica", "doença renal policística", "FIP (peritonite infecciosa felina)"],
        "exercise_needs": "Leve. São relaxados e não muito ativos. Gostam de brincar mas não por muito tempo. Brinquedos suaves são preferidos.",
        "feeding_guide": "Adultos: 70-100g de ração premium por dia em 2 refeições. Ração de alta qualidade para manter pelagem e saúde cardíaca.",
        "care_tips": ["Escovação 2 vezes por semana", "Exames cardíacos regulares", "Enriquecimento ambiental suave", "Muita atenção e carinho"],
        "ideal_environment": "Ótimo para apartamentos. São conhecidos por 'soltar como trapos' quando carregados (daí o nome). Ótimos para crianças e iniciantes.",
        "description": "O Ragdoll é chamado assim porque fica completamente relaxado (como um boneco de pano) quando carregado nos braços. É um gato grande, calmo e extremamente dócil. Sua natureza gentil e tolerante o torna excelente para famílias com crianças.",
    },
    {
        "species": "cat",
        "name": "Bengal",
        "name_en": "Bengal",
        "origin": "Estados Unidos",
        "size": "medium",
        "weight_range": "3,5-7 kg",
        "life_expectancy": "12-16 anos",
        "temperament": ["ativo", "atlético", "curioso", "inteligente", "brincalhão", "vocal"],
        "energy_level": 5,
        "grooming_level": 1,
        "health_issues": ["cardiomiopatia hipertrófica", "atrofia progressiva da retina", "anemia hemolítica"],
        "exercise_needs": "Alto. Extremamente ativo e atlético. Precisa de muito espaço, postes altos de escalada e brinquedos que estimulem seus instintos de caçador.",
        "feeding_guide": "Adultos: 60-80g de ração premium por dia em 2-3 refeições. Ração de alta proteína condizente com seu nível de atividade.",
        "care_tips": ["Arranhadores e árvores de gato altas", "Brinquedos interativos diários", "Pode ser treinado com coleira", "Precisa de muito espaço"],
        "ideal_environment": "Prefere ambientes espaçosos. Não é recomendado para apartamentos pequenos. Gosta de água (herdado do gato-leopardo asiático).",
        "description": "O Bengal foi criado através do cruzamento de gatos domésticos com o gato-leopardo asiático selvagem. Tem padrão de pelagem exótico que lembra um leopardo. É extremamente ativo e curioso, com instintos selvagens marcantes. Requer tutores ativos e ambientes estimulantes.",
    },
    {
        "species": "cat",
        "name": "British Shorthair",
        "name_en": "British Shorthair",
        "origin": "Reino Unido",
        "size": "medium",
        "weight_range": "3,5-8 kg",
        "life_expectancy": "12-17 anos",
        "temperament": ["calmo", "paciente", "independente", "leal", "adaptável", "tranquilo"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["cardiomiopatia hipertrófica", "doença renal policística", "hemofilia B"],
        "exercise_needs": "Leve a moderado. São calmos mas apreciam brincadeiras curtas. Brinquedos interativos e arranhadores são suficientes.",
        "feeding_guide": "Adultos: 60-80g de ração premium por dia em 2 refeições. Propenso ao sobrepeso - controlar porções.",
        "care_tips": ["Escovação semanal", "Controle de peso", "Exames cardíacos regulares", "Brinquedos interativos"],
        "ideal_environment": "Ótimo para apartamentos. É independente e tolera bem a solidão. Bom para quem trabalha fora. Perfeito para donos de primeira viagem.",
        "description": "O British Shorthair é o gato plushie perfeito - redondo, peludo e com expressão de boneco. É calmo, independente e adaptável. Apesar de afetivo, não é um gato de colo. Muito popular como primeiro gato por seu temperamento equilibrado e facilidade de cuidado.",
    },
    {
        "species": "cat",
        "name": "Abissínio",
        "name_en": "Abyssinian",
        "origin": "Etiópia (antiga Abissínia)",
        "size": "medium",
        "weight_range": "3-5 kg",
        "life_expectancy": "9-15 anos",
        "temperament": ["ativo", "curioso", "brincalhão", "inteligente", "ágil", "sociável"],
        "energy_level": 5,
        "grooming_level": 1,
        "health_issues": ["atrofia progressiva da retina", "doença renal amiloide", "problemas dentários"],
        "exercise_needs": "Alto. Extremamente ativo e ágil. Precisa de muito espaço, árvores de gato e brinquedos para se exercitar.",
        "feeding_guide": "Adultos: 50-70g de ração premium por dia em 2-3 refeições. Manter em forma pois é naturalmente atlético.",
        "care_tips": ["Árvores de gato altas", "Muitos brinquedos interativos", "Escovação simples semanal", "Enriquecimento ambiental constante"],
        "ideal_environment": "Prefere apartamentos espaçosos ou casas. Não gosta de ambientes pequenos. Muito ativo e inteligente - precisa de estimulação constante.",
        "description": "O Abissínio é considerado um dos gatos mais antigos do mundo, com aparência que lembra um gato selvagem egípcio. É extremamente ativo, curioso e inteligente. Adora explorar e subir em lugares altos. Não é um gato de colo, mas é muito afetuoso à sua maneira.",
    },
    {
        "species": "cat",
        "name": "Scottish Fold",
        "name_en": "Scottish Fold",
        "origin": "Escócia",
        "size": "medium",
        "weight_range": "2,7-6 kg",
        "life_expectancy": "11-15 anos",
        "temperament": ["calmo", "adaptável", "gentil", "sociável", "leal", "brincalhão"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["osteocondrodisplasia (problemas ósseos graves)", "artrite severa", "cardiomiopatia hipertrófica"],
        "exercise_needs": "Leve a moderado. Não são muito ativos. Gostam de brincar mas em ritmo calmo. Atenção aos sinais de dor articular.",
        "feeding_guide": "Adultos: 50-70g de ração premium por dia em 2 refeições. Suplementação com ômega-3 pode ajudar nas articulações.",
        "care_tips": ["Monitorar sinais de dor nas articulações", "Escovação semanal", "Evitar exercícios intensos", "Exames ortopédicos regulares"],
        "ideal_environment": "Ótimo para apartamentos. Adapta-se bem a qualquer ambiente. Controvérsia ética pela mutação genética que causa problemas de saúde.",
        "description": "O Scottish Fold é facilmente reconhecível por suas orelhas dobradas para frente, resultado de uma mutação genética. É calmo e adaptável, mas a raça é controversa eticamente pois a mutação causa problemas ósseos severos. Escolha criar com responsabilidade.",
    },
    {
        "species": "cat",
        "name": "Devon Rex",
        "name_en": "Devon Rex",
        "origin": "Reino Unido",
        "size": "small",
        "weight_range": "2,5-4,5 kg",
        "life_expectancy": "9-15 anos",
        "temperament": ["travesso", "ativo", "curioso", "carinhoso", "sociável", "inteligente"],
        "energy_level": 4,
        "grooming_level": 1,
        "health_issues": ["miopatia do Devon Rex", "luxação de patela", "problemas dentários", "hipotireoidismo"],
        "exercise_needs": "Moderado a alto. Muito ativo e brincalhão. Gosta de subir em lugares altos e brincar com brinquedos interativos.",
        "feeding_guide": "Adultos: 50-70g de ração premium por dia em 2-3 refeições. Metabolismo acelerado - monitorar peso.",
        "care_tips": ["Limpeza das orelhas semanal", "Escovação mínima (pelo curto e encaracolado)", "Brinquedos interativos", "Ambiente aquecido (são sensíveis ao frio)"],
        "ideal_environment": "Ótimo para apartamentos. Adora estar com pessoas e não gosta de ficar sozinho. Perfeito para quem fica em casa.",
        "description": "O Devon Rex é um gato elfo com orelhas grandes, olhos imensos e pelo encaracolado e suave. É extremamente travesso e curioso, sempre inventando traquinagens. Muito afetuoso, adora ficar no colo e se aquece com o calor corporal dos tutores.",
    },
    {
        "species": "cat",
        "name": "Sphynx",
        "name_en": "Sphynx",
        "origin": "Canadá",
        "size": "medium",
        "weight_range": "3,5-7 kg",
        "life_expectancy": "8-14 anos",
        "temperament": ["extrovertido", "energético", "curioso", "afetuoso", "inteligente", "brincalhão"],
        "energy_level": 4,
        "grooming_level": 3,
        "health_issues": ["cardiomiopatia hipertrófica", "problemas de pele", "doença muscular hereditária", "problemas dentários"],
        "exercise_needs": "Moderado a alto. Apesar de sem pelos, é muito ativo e brincalhão. Precisa de estimulação e brinquedos.",
        "feeding_guide": "Adultos: 70-90g de ração premium por dia em 2-3 refeições. Metabolismo mais acelerado para manter a temperatura corporal.",
        "care_tips": ["Banho semanal para remover oleosidade", "Limpeza de orelhas frequente", "Proteger do frio e sol", "Exames cardíacos regulares"],
        "ideal_environment": "Ótimo para apartamentos aquecidos. Sensível ao frio e ao sol. Não deve ter acesso ao exterior sem supervisão.",
        "description": "O Sphynx, apesar de parecer nu, tem uma camada fina de pelos quase imperceptíveis. É surpreendentemente quente ao toque. Extremamente extrovertido e afetuoso, é considerado o 'cachorro dos gatos'. Muito vocal e sociável, adora atenção e não gosta de ficar sozinho.",
    },
    {
        "species": "cat",
        "name": "Angorá Turco",
        "name_en": "Turkish Angora",
        "origin": "Turquia",
        "size": "medium",
        "weight_range": "2,5-5 kg",
        "life_expectancy": "12-18 anos",
        "temperament": ["inteligente", "ativo", "curioso", "afetuoso", "extrovertido", "brincalhão"],
        "energy_level": 4,
        "grooming_level": 3,
        "health_issues": ["surdez (especialmente brancos de olhos azuis)", "cardiomiopatia hipertrófica", "ataxia"],
        "exercise_needs": "Moderado a alto. Muito ativo e curioso. Adora explorar e escalar. Precisa de árvores de gato e brinquedos.",
        "feeding_guide": "Adultos: 50-70g de ração premium por dia em 2 refeições. Boa alimentação para manter a beleza da pelagem.",
        "care_tips": ["Escovação 2-3 vezes por semana", "Teste de audição (especialmente em brancos)", "Brinquedos interativos", "Estimulação mental"],
        "ideal_environment": "Adapta-se bem a apartamentos e casas. É elegante e gracioso. Um dos gatos mais antigos do mundo.",
        "description": "O Angorá Turco é uma das raças mais antigas do mundo, proveniente da Turquia. Com sua pelagem branca (ou de outras cores) e sedosa, e olhos que podem ser de cores diferentes, é considerado um dos gatos mais belos. Inteligente e ativo, é um companheiro elegante.",
    },
    {
        "species": "cat",
        "name": "Birmanês",
        "name_en": "Birman",
        "origin": "Birmânia (Mianmar)/França",
        "size": "medium",
        "weight_range": "3-7 kg",
        "life_expectancy": "12-16 anos",
        "temperament": ["gentil", "calmo", "sociável", "afetivo", "curioso", "adaptável"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["cardiomiopatia hipertrófica", "doença renal policística", "problemas de tireoide"],
        "exercise_needs": "Leve a moderado. São calmos mas gostam de brincar. Brinquedos interativos e arranhadores são suficientes.",
        "feeding_guide": "Adultos: 60-80g de ração premium por dia em 2 refeições. Atenção ao peso.",
        "care_tips": ["Escovação semanal", "Limpeza das patas brancas", "Exames cardíacos regulares", "Brinquedos interativos"],
        "ideal_environment": "Ótimo para apartamentos. Sociável e se dá bem com outros gatos e cães. Bom para famílias.",
        "description": "O Birmanês, também chamado de Sagrado da Birmânia, é um gato de aparência majestosa com pelagem colorpoint e patas brancas características. É calmo, gentil e muito sociável. Desenvolve vínculos fortes com toda a família e se dá muito bem com outros animais.",
    },
    {
        "species": "cat",
        "name": "Burmês",
        "name_en": "Burmese",
        "origin": "Birmânia (Mianmar)/Estados Unidos",
        "size": "medium",
        "weight_range": "3,5-6,5 kg",
        "life_expectancy": "16-18 anos",
        "temperament": ["afetuoso", "curioso", "brincalhão", "sociável", "vocal", "enérgico"],
        "energy_level": 4,
        "grooming_level": 1,
        "health_issues": ["diabetes", "hipocalemia (fraqueza muscular)", "defeitos craniofaciais"],
        "exercise_needs": "Moderado. Ativo e brincalhão por toda a vida. Gosta de brinquedos interativos e companhia humana.",
        "feeding_guide": "Adultos: 60-80g de ração premium por dia em 2-3 refeições. Monitorar sinais de diabetes.",
        "care_tips": ["Brinquedos interativos", "Muita atenção e carinho", "Escovação simples semanal", "Não gosta de ficar sozinho"],
        "ideal_environment": "Ótimo para apartamentos. Muito sociável e ama a companhia humana. Considere adotar dois para evitar solidão.",
        "description": "O Burmês é um gato completamente marrom com olhos dourados que emana uma presença suave e amorosa. É extremamente sociável e muitas vezes descrito como um 'gato-cão' por seguir os tutores pela casa. Muito vocal, expressa afeto constantemente.",
    },
    {
        "species": "cat",
        "name": "Norwegian Forest Cat",
        "name_en": "Norwegian Forest Cat",
        "origin": "Noruega",
        "size": "large",
        "weight_range": "4-9 kg",
        "life_expectancy": "14-16 anos",
        "temperament": ["calmo", "gentil", "independente", "brincalhão", "adaptável", "robusto"],
        "energy_level": 3,
        "grooming_level": 3,
        "health_issues": ["cardiomiopatia hipertrófica", "glicogenose tipo IV", "displasia de quadril"],
        "exercise_needs": "Moderado. Gosta de escalar e explorar. Árvores de gato e sacadas com tela são ideais para este amante da natureza.",
        "feeding_guide": "Adultos: 70-100g de ração premium por dia em 2 refeições. Boa alimentação para manter a densa pelagem.",
        "care_tips": ["Escovação 2-3 vezes por semana", "Arranhadores e postes altos", "Acesso seguro ao exterior se possível", "Exames cardíacos regulares"],
        "ideal_environment": "Prefere ambientes espaçosos ou casas com jardim. Adapta-se a apartamentos se tiver postes de escalada e sacada telada.",
        "description": "O Norwegian Forest Cat (Skogkatt) é o gato da floresta norueguesa, adaptado ao clima ártico com sua densa pelagem dupla. É robusto, ágil e independente, mas também muito gentil e afetuoso. Adora escalar e tem instintos de caçador bem desenvolvidos.",
    },
    {
        "species": "cat",
        "name": "Savannah",
        "name_en": "Savannah",
        "origin": "Estados Unidos",
        "size": "large",
        "weight_range": "3,5-11 kg",
        "life_expectancy": "12-20 anos",
        "temperament": ["ativo", "curioso", "leal", "sociável", "aventureiro", "inteligente"],
        "energy_level": 5,
        "grooming_level": 1,
        "health_issues": ["cardiomiopatia hipertrófica", "sensibilidades a anestesia", "problemas digestivos"],
        "exercise_needs": "Muito alto. É parcialmente selvagem (descendente do serval africano). Precisa de muito espaço, estimulação e até pode ser treinado com coleira.",
        "feeding_guide": "Adultos: 80-120g de ração premium de alta proteína por dia em 2-3 refeições. Dieta rica em proteína animal.",
        "care_tips": ["Grande espaço para explorar", "Pode ser treinado com coleira", "Muito estimulação mental e física", "Não para donos inexperientes"],
        "ideal_environment": "Precisa de muito espaço. Não recomendado para apartamentos pequenos. Pode ser perigoso para outros animais de pequeno porte.",
        "description": "O Savannah é um híbrido entre o gato doméstico e o serval africano, sendo um dos gatos mais exóticos e caros do mundo. As primeiras gerações (F1, F2) têm comportamentos muito próximos ao selvagem. É extremamente ativo, curioso e inteligente. Requer tutores experientes.",
    },
    {
        "species": "cat",
        "name": "Russo Azul",
        "name_en": "Russian Blue",
        "origin": "Rússia",
        "size": "medium",
        "weight_range": "3,5-7 kg",
        "life_expectancy": "15-20 anos",
        "temperament": ["gentil", "reservado", "inteligente", "leal", "calmo", "curioso"],
        "energy_level": 2,
        "grooming_level": 1,
        "health_issues": ["obesidade", "problemas dentários", "cardiomiopatia hipertrófica"],
        "exercise_needs": "Leve a moderado. Calmo mas gosta de brincar. Brinquedos interativos e momentos de brincadeira são bem-vindos.",
        "feeding_guide": "Adultos: 50-70g de ração premium por dia em 2 refeições. Muito propenso à obesidade - controlar rigorosamente as porções.",
        "care_tips": ["Escovação simples semanal", "Controle de peso rigoroso", "Ambiente tranquilo", "Brinquedos interativos para estimulação"],
        "ideal_environment": "Ótimo para apartamentos tranquilos. Prefere ambientes calmos e rotineiros. Demora a se adaptar a mudanças.",
        "description": "O Russo Azul é famoso por sua pelagem azul-prateada densa e seus olhos verde-esmeralda. É um gato reservado e tímido com estranhos, mas extremamente leal e carinhoso com a família. Ótimo para alérgicos pois produz menos Fel d 1 que outras raças.",
    },
    {
        "species": "cat",
        "name": "Exotic Shorthair",
        "name_en": "Exotic Shorthair",
        "origin": "Estados Unidos",
        "size": "medium",
        "weight_range": "3,5-7 kg",
        "life_expectancy": "12-15 anos",
        "temperament": ["calmo", "afetuoso", "leal", "brincalhão", "pacífico", "adaptável"],
        "energy_level": 2,
        "grooming_level": 2,
        "health_issues": ["síndrome braquicefálica", "doença renal policística", "cardiomiopatia hipertrófica", "problemas oculares"],
        "exercise_needs": "Leve. Similar ao Persa mas um pouco mais ativo. Brincadeiras curtas e brinquedos suaves são ideais.",
        "feeding_guide": "Adultos: 50-80g de ração premium por dia em 2 refeições. Ração para braquicefálicos ajuda na alimentação.",
        "care_tips": ["Limpeza diária dos olhos", "Escovação semanal", "Limpeza das dobras faciais", "Exames cardíacos regulares"],
        "ideal_environment": "Perfeito para apartamentos. É o 'Persa preguiçoso' - tem a aparência do Persa com pelo curto e manutenção mais fácil.",
        "description": "O Exotic Shorthair é essencialmente um Persa com pelo curto. Foi criado para ter todo o charme do Persa com a facilidade de manutenção do pelo curto. É calmo, afetuoso e adaptável, sendo ótimo para quem ama o Persa mas tem pouco tempo para cuidados intensivos.",
    },
    {
        "species": "cat",
        "name": "Ocicat",
        "name_en": "Ocicat",
        "origin": "Estados Unidos",
        "size": "medium",
        "weight_range": "3-6,5 kg",
        "life_expectancy": "10-15 anos",
        "temperament": ["ativo", "curioso", "sociável", "confiante", "leal", "adaptável"],
        "energy_level": 4,
        "grooming_level": 1,
        "health_issues": ["cardiomiopatia hipertrófica", "doença hepática amiloide", "diabetes"],
        "exercise_needs": "Moderado a alto. Ativo e curioso, gosta de explorar e brincar. Brinquedos interativos e companhia são importantes.",
        "feeding_guide": "Adultos: 60-80g de ração premium por dia em 2 refeições. Dieta equilibrada para manter o porte atlético.",
        "care_tips": ["Escovação simples semanal", "Muitos brinquedos interativos", "Companhia frequente", "Estimulação mental"],
        "ideal_environment": "Adapta-se bem a apartamentos e casas. É sociável e se dá bem com outros animais. Ótimo para famílias ativas.",
        "description": "O Ocicat tem aparência de gato selvagem (semelhante ao ocelote), mas é 100% doméstico. Foi criado acidentalmente durante experimentos para criar um Siamês colorpoint. É ativo, sociável e confiante, com um padrão de manchas exótico que impressiona.",
    },
    {
        "species": "cat",
        "name": "Balinês",
        "name_en": "Balinese",
        "origin": "Estados Unidos",
        "size": "medium",
        "weight_range": "2,5-5 kg",
        "life_expectancy": "12-18 anos",
        "temperament": ["inteligente", "curioso", "sociável", "vocal", "afetuoso", "brincalhão"],
        "energy_level": 4,
        "grooming_level": 2,
        "health_issues": ["amiloidose hepática", "cardiomiopatia dilatada", "estrabismo convergente"],
        "exercise_needs": "Moderado a alto. Semelhante ao Siamês em termos de energia. Muito brincalhão e ativa até a velhice.",
        "feeding_guide": "Adultos: 50-70g de ração premium por dia em 2-3 refeições. Manter dieta equilibrada.",
        "care_tips": ["Escovação 2 vezes por semana", "Brinquedos interativos", "Muita atenção e interação", "Não deixar sozinho por muito tempo"],
        "ideal_environment": "Ótimo para apartamentos com família presente. É o Siamês de pelo longo - igualmente vocal e social.",
        "description": "O Balinês é essencialmente um Siamês de pelo longo, surgido de uma mutação natural na raça Siamesa. É igualmente vocal, inteligente e afetuoso. Sua pelagem semi-longa é sedosa e relativamente fácil de manter. É um companheiro extremamente ativo e comunicativo.",
    },
    {
        "species": "cat",
        "name": "Doméstico (SRD)",
        "name_en": "Domestic Cat (Mixed Breed)",
        "origin": "Mundial",
        "size": "medium",
        "weight_range": "3-6 kg",
        "life_expectancy": "15-20 anos",
        "temperament": ["variável", "adaptável", "independente", "curioso", "resiliente", "versátil"],
        "energy_level": 3,
        "grooming_level": 2,
        "health_issues": ["doenças comuns como calicivírus", "rinotraqueíte", "leucemia felina", "FIV"],
        "exercise_needs": "Variável. Geralmente mais resistentes e ativos que raças puras. Brinquedos interativos e estimulação são importantes.",
        "feeding_guide": "Adultos: 60-80g de ração premium por dia em 2 refeições. Gatos SRD geralmente têm menos restrições alimentares que raças puras.",
        "care_tips": ["Vacinação em dia", "Castração recomendada", "Escovação semanal", "Enriquecimento ambiental"],
        "ideal_environment": "Adapta-se a qualquer ambiente. São os gatos mais robustos e saudáveis graças à diversidade genética. Adoção é sempre a melhor opção!",
        "description": "O gato SRD (Sem Raça Definida) ou doméstico é o gato mais popular do Brasil. Graças à sua diversidade genética, tende a ser mais saudável e resiliente que muitas raças puras. Cada SRD é único e especial. Adotar um gato de rua é um ato de amor que salva vidas.",
    },
]

ALL_BREEDS = DOG_BREEDS + CAT_BREEDS
